lints.workspace = true

[package]
name = "gix-blame"
version = "0.2.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dedicated to implementing a 'blame' algorithm"
authors = ["Christoph Rüßler <christoph.ruessler@mailbox.org>", "Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.70"

[lib]
doctest = false

[dependencies]
gix-commitgraph = { version = "^0.28.0", path = "../gix-commitgraph" }
gix-revwalk = { version = "^0.20.0", path = "../gix-revwalk" }
gix-trace = { version = "^0.1.12", path = "../gix-trace" }
gix-date = { version = "^0.10.1", path = "../gix-date" }
gix-diff = { version = "^0.52.0", path = "../gix-diff", default-features = false, features = ["blob"] }
gix-object = { version = "^0.49.0", path = "../gix-object" }
gix-hash = { version = "^0.18.0", path = "../gix-hash" }
gix-worktree = { version = "^0.41.0", path = "../gix-worktree", default-features = false, features = ["attributes"] }
gix-traverse = { version = "^0.46.0", path = "../gix-traverse" }

smallvec = "1.15.0"
thiserror = "2.0.0"

[dev-dependencies]
gix-ref = { path = "../gix-ref" }
gix-filter = { path = "../gix-filter" }
gix-fs = { path = "../gix-fs" }
gix-index = { path = "../gix-index" }
gix-odb = { path = "../gix-odb" }
gix-testtools = { path = "../tests/tools" }
