lints.workspace = true

[package]
name = "gix-submodule"
version = "0.20.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing git submodules"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.70"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-pathspec = { version = "^0.12.0", path = "../gix-pathspec" }
gix-refspec = { version = "^0.31.0", path = "../gix-refspec" }
gix-config = { version = "^0.46.0", path = "../gix-config" }
gix-path = { version = "^0.10.20", path = "../gix-path" }
gix-url = { version = "^0.32.0", path = "../gix-url" }

bstr = { version = "1.12.0", default-features = false }
thiserror = "2.0.0"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-features = { path = "../gix-features", features = ["walkdir"] }
