lints.workspace = true

[package]
name = "gix-traverse"
version = "0.50.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.82"
autotests = false

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.21.0", path = "../gix-hash" }
gix-object = { version = "^0.53.0", path = "../gix-object" }
gix-date = { version = "^0.11.1", path = "../gix-date" }
gix-hashtable = { version = "^0.11.0", path = "../gix-hashtable" }
gix-revwalk = { version = "^0.24.0", path = "../gix-revwalk" }
gix-commitgraph = { version = "^0.31.0", path = "../gix-commitgraph" }
smallvec = "1.15.1"
thiserror = "2.0.17"
bitflags = "2"
