lints.workspace = true

[package]
name = "gix-worktree-state"
version = "0.24.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing setting the worktree to a particular state"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.82"
autotests = false

[lib]
doctest = false

[dependencies]
gix-worktree = { version = "^0.46.0", path = "../gix-worktree", default-features = false, features = ["attributes"] }
gix-index = { version = "^0.45.1", path = "../gix-index" }
gix-fs = { version = "^0.18.2", path = "../gix-fs" }
gix-object = { version = "^0.54.1", path = "../gix-object" }
gix-path = { version = "^0.10.22", path = "../gix-path" }
gix-features = { version = "^0.45.2", path = "../gix-features" }
gix-filter = { version = "^0.24.1", path = "../gix-filter" }

io-close = "0.3.7"
thiserror = "2.0.17"
bstr = { version = "1.12.0", default-features = false }
