lints.workspace = true

[package]
name = "gix-worktree-stream"
version = "0.26.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "generate a byte-stream from a git-tree"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.82"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-features = { version = "^0.45.1", path = "../gix-features", features = ["progress", "io-pipe"] }
gix-hash = { version = "^0.21.1", path = "../gix-hash" }
gix-object = { version = "^0.54.0", path = "../gix-object" }
gix-attributes = { version = "^0.29.0", path = "../gix-attributes" }
gix-filter = { version = "^0.24.0", path = "../gix-filter" }
gix-traverse = { version = "^0.51.0", path = "../gix-traverse" }
gix-fs = { version = "^0.18.1", path = "../gix-fs" }
gix-path = { version = "^0.10.22", path = "../gix-path" }

thiserror = "2.0.17"
parking_lot = "0.12.4"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-odb = { path = "../gix-odb" }
gix-worktree = { path = "../gix-worktree", default-features = false, features = ["attributes"] }
