lints.workspace = true

[package]
name = "gix-worktree-stream"
version = "0.21.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "generate a byte-stream from a git-tree"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.70"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-features = { version = "^0.42.0", path = "../gix-features", features = ["progress", "io-pipe"] }
gix-hash = { version = "^0.17.1", path = "../gix-hash" }
gix-object = { version = "^0.49.0", path = "../gix-object" }
gix-attributes = { version = "^0.25.0", path = "../gix-attributes" }
gix-filter = { version = "^0.19.0", path = "../gix-filter" }
gix-traverse = { version = "^0.46.0", path = "../gix-traverse" }
gix-fs = { version = "^0.14.0", path = "../gix-fs" }
gix-path = { version = "^0.10.15", path = "../gix-path" }

thiserror = "2.0.0"
parking_lot = "0.12.1"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-odb = { path = "../gix-odb" }
gix-worktree = { path = "../gix-worktree", default-features = false, features = ["attributes"] }
